  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/charlenecordero/ai-portfolio:$COMMIT_SHA', '.']
  
  # 2. Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/charlenecordero/ai-portfolio:$COMMIT_SHA']
  
  # 3. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ai-portfolio'
      - '--image'
      - 'gcr.io/$PROJECT_ID/github.com/charlenecordero/ai-portfolio:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
images:
  - 'gcr.io/$PROJECT_ID/github.com/charlenecordero/ai-portfolio:$COMMIT_SHA'
